[[redirects]]
  from = "index.html"
  to = "/ticket"
  status = 301
  force = true

  [[redirects]]
  from = "home.html"
  to = "/ticket"
  status = 301
  force = true

  [[redirects]]
  from = "/ticket"
  to = "/ticket.html"
  status = 200
  force = true